- es.json
Hi great product adding my little grain of salt!
Would love my users can use it in Spanish too!
> Add Spanish Language to InStatus

- vi.json
I love Instatus so much. Much better than Statuspage.io. Love from Vietnam.
> Add Vietnamese (vi.json)

- si.json
Strings are updated to be more natural.
> Update SI strings

- da.json
Seeing the phrases on the site identified some contextual gibberish. These changes should fix this.
> Fixed some phrasing that works better in context

- da.json
> Add a missing space between two words

- si.json
Fixed some translations to make it more natural.
> Update to sl translations

- rs.json
> Fixed spelling

- README.md
I added a link to my GitHub profile
> Added link to Aleksandar Vasilić

- de.json
> Update German translation

- fr.json
Hello,
I corrected many French mistakes in the translation.
Have a nice day !
> Update fr.json I Correction of errors

- tr.json
Fixed a translation that didn't make sense in Turkish.
> Fix a wrong translition in Turkish

- zh.json
for Chinese (Simplified)
Improved a few translations
Shortened a few translations to fit on page display
> improve Chinese translation && optimize for page display

- it.json
> Updated Italian Language

- it.json
Changed some things for better traduction.
> New update Italian Language

- nl.json
Hi, 
I have made some suggestions to NL strings, so that it sounds more native and that more common words are used.
> Replace some NL translations to use more common used terms

- zh-tw.json
- zh.json
> 📖 Improve CHS CHT

- zh-tw.json
- zh.json
By the way, my status page needs to be updated to the latest version, because the copyright in the lower right corner is not right
[CC的状态页](https://cc.instatus.com/)
And don 't know if due to the time zone problem, the day of the problem does not correspond to the color
> 🔧 Update CHS & CHT

- si.json
Updated `getUpdates` translation to better reflect the meaning.
> Better translation for getUpdates

- de.json
I made a revision yesterday and only noticed today that it is not displayed correctly on the website for German.
> Improved the translation (see "copied")

- .env.example
- .gitignore
- README.md
- index.js
- package.json
I've added support for .env so that you don't commit your API Key by mistake ;-)
> Support .env file

- ja.json
Changed the translation of `lastUpdated` to a more general expression.
> fix `lastUpdated` [JPN]

- README.md
It's been a while since I changed my site's domain name. 
Please update the link in the credits. 
I did the translation in #42 pull request.
> Update translation author's website

- ru.json
> Russian translation improvements
